---
- name: Установка и запуск x-ui
  hosts: all
  become: true

  tasks:
    - name: Установить необходимые пакеты
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Создать директории для x-ui
      file:
        path: /opt/x-ui/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - data
        - certificates
        - logs

    - name: Создать docker-compose.yml файл
      copy:
        dest: /opt/x-ui/docker-compose.yml
        content: |
          services:
            x-ui:
              image: bigbugcc/3x-ui:v2.8.5
              container_name: 3x-ui
              restart: unless-stopped
              ports:
                - "127.0.0.1:2053:2053"
                - "2096:2096"
                - "443:443"
              volumes:
                - ./data:/etc/x-ui
                - ./certificates:/root/cert
                - ./logs:/var/log/x-ui
              environment:
                - TZ=Europe/Moscow
                - XRAY_ENABLE=true
              cap_add:
                - NET_ADMIN
              sysctls:
                - net.ipv6.conf.all.disable_ipv6=0
              command: /app/x-ui bin -l ru

    - name: Запустить контейнер через docker-compose
      command: docker-compose up -d
      args:
        chdir: /opt/x-ui